import { useFormContext } from "react-hook-form";

export default function DemographicsStep() {
  const { register, formState: { errors } } = useFormContext();
  const e = errors.demographics || {};

  return (
    <div className="space-y-6">
      <h3 className="text-base font-semibold text-gray-800">Demographics</h3>
      
      <div className="grid grid-cols-2 gap-4">
        {/* Date of Birth */}
        <div>
          <label className="form-label">Date of Birth *</label>
          <input type="date" className="form-input"
            {...register("demographics.date_of_birth", {
              required: "Date of birth is required",
              onChange: (ev) => {
                // Auto-calculate age
                const dob = new Date(ev.target.value);
                const age = Math.floor((Date.now() - dob) / (365.25 * 24 * 60 * 60 * 1000));
                // We set age via hidden field — handled in PatientForm
              }
            })}
          />
          {e.date_of_birth && <p className="form-error">{e.date_of_birth.message}</p>}
        </div>

        {/* Age (auto-calculated but editable) */}
        <div>
          <label className="form-label">Age *</label>
          <input type="number" className="form-input" min={0} max={150}
            {...register("demographics.age", {
              required: "Age is required",
              valueAsNumber: true,
              min: { value: 0, message: "Age must be positive" },
            })}
          />
          {e.age && <p className="form-error">{e.age.message}</p>}
        </div>

        {/* Gender */}
        <div>
          <label className="form-label">Gender *</label>
          <select className="form-input" {...register("demographics.gender", { required: true })}>
            <option value="unknown">Unknown</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="other">Other</option>
          </select>
        </div>

        {/* Race */}
        <div>
          <label className="form-label">Race / Ethnicity</label>
          <input type="text" className="form-input" placeholder="e.g. White, Hispanic"
            {...register("demographics.race")} />
        </div>

        {/* Marital Status */}
        <div>
          <label className="form-label">Marital Status</label>
          <input type="text" className="form-input" placeholder="e.g. Married, Single"
            {...register("demographics.marital_status")} />
        </div>

        {/* City */}
        <div>
          <label className="form-label">City</label>
          <input type="text" className="form-input" {...register("demographics.city")} />
        </div>

        {/* State */}
        <div>
          <label className="form-label">State</label>
          <input type="text" className="form-input" {...register("demographics.state")} />
        </div>

        {/* Country */}
        <div>
          <label className="form-label">Country</label>
          <input type="text" className="form-input" placeholder="e.g. US"
            {...register("demographics.country")} />
        </div>
      </div>

      <p className="text-xs text-gray-400">* Patient ID will be auto-generated by the system.</p>
    </div>
  );
}